CXX = g++
RC = windres
CXXFLAGS = -O3 -mwindows -municode -Wall -Wextra -std=c++17 -Isrc
LDFLAGS = -liphlpapi -lgdi32 -ldwmapi -lpdh -lpsapi -lshell32 -lcomctl32 -lcomdlg32 -lole32 -loleaut32 -lwbemuuid

SRCS = src/Config.cpp \
       src/Theme.cpp \
       src/Metrics.cpp \
       src/Renderer.cpp \
       src/TaskbarSync.cpp \
       src/SettingsWindow.cpp \
       src/License.cpp \
       src/Main.cpp

OBJS = $(SRCS:.cpp=.o) src/TaskbarMonitor.res.o
TARGET = TaskbarMonitor.exe

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(CXXFLAGS) $(LDFLAGS)

src/TaskbarMonitor.res.o: src/TaskbarMonitor.rc src/TaskbarMonitor.manifest
	$(RC) -i src/TaskbarMonitor.rc -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f src/*.o src/*.res.o $(TARGET)

.PHONY: all clean